INSERT INTO Bar (Details,DateAdded,Name,Rating,Picture,Location)
VALUES
  ("in consectetuer ipsum nunc id","09.30.22","piano opportunity malt",3,"/picture","South Burlington"),
  ("gravida sit amet, dapibus id,","09.06.22","green place",2,"/picture","Pocatello"),
  ("faucibus. Morbi","10.07.22","grey blue",3,"/picture","Tuscaloosa"),
  ("Nullam vitae diam. Proin dolor. Nulla semper tellus id","10.30.22","orange depth",2,"/picture","North Las Vegas"),
  ("magna a","10.20.22","ale combination owner",5,"/picture","Bozeman"),
  ("orci tincidunt adipiscing.","11.14.22","wealth strategy",2,"/picture","Kansas City"),
  ("urna suscipit nonummy. Fusce fermentum","11.12.22","opportunity malt",2,"/picture","Wilmington"),
  ("bibendum sed, est. Nunc","10.25.22","control piano opportunity",2,"/picture","Chattanooga"),
  ("Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus","09.12.22","law fortune",4,"/picture","Huntsville"),
  ("malesuada malesuada. Integer id magna et","11.26.22","combination owner",1,"/picture","Louisville"),
  ("venenatis a, magna. Lorem ipsum dolor sit amet,","10.24.22","grey blue",1,"/picture","Lansing"),
  ("aliquet. Phasellus","09.16.22","history dinner",5,"/picture","Duluth"),
  ("a purus. Duis elementum, dui quis accumsan convallis,","10.29.22","strategy bread",5,"/picture","San Antonio"),
  ("vehicula aliquet libero. Integer in magna.","10.08.22","red green",3,"/picture","Gulfport"),
  ("risus. Donec egestas. Duis ac arcu. Nunc","10.06.22","blue red",1,"/picture","Kearney"),
  ("pede blandit congue. In scelerisque scelerisque dui. Suspendisse","09.27.22","combination owner storage",3,"/picture","Aurora"),
  ("posuere, enim nisl elementum purus, accumsan interdum libero","11.17.22","place beers",2,"/picture","Tampa"),
  ("purus mauris","11.18.22","bread idea",4,"/picture","Ketchikan"),
  ("egestas. Aliquam fringilla cursus purus. Nullam scelerisque","09.28.22","brewing company",3,"/picture","Erie"),
  ("tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris","11.21.22","orange depth flight",0,"/picture","Newark");
