INSERT INTO Beer (DateAdded,Type,Cost,Comments,Picture,AlcVol,Name)
VALUES
  ("10.13.22","Amber-Ale",12,"est arcu ac orci. Ut","/picture",4,"company guerilla"),
  ("09.16.22","Pale-Ale",15,"placerat eget, venenatis a, magna. Lorem ipsum dolor","/picture",28,"appearance indication"),
  ("10.24.22","Barley-Wine",18,"Nulla tincidunt, neque vitae semper","/picture",22,"chemistry control"),
  ("09.21.22","Ale",4,"mauris, aliquam eu, accumsan sed, facilisis vitae, orci.","/picture",8,"appearance indication"),
  ("11.24.22","Stout",7,"imperdiet non, vestibulum nec, euismod","/picture",13,"idea ratio"),
  ("11.04.22","Altbier",7,"Proin sed turpis nec mauris blandit","/picture",5,"outcome history"),
  ("09.02.22","Altbier",6,"neque. Sed","/picture",12,"lab chemistry"),
  ("10.04.22","Altbier",7,"tempus eu, ligula. Aenean euismod","/picture",11,"mud law"),
  ("09.29.22","Witbier",7,"molestie. Sed id risus quis diam luctus","/picture",5,"contribution orange"),
  ("09.16.22","Imperial-Stout",9,"metus. In lorem. Donec elementum, lorem ut aliquam iaculis,","/picture",20,"blue red"),
  ("11.20.22","Fruit-Beer",4,"torquent per conubia nostra,","/picture",17,"grey blue"),
  ("10.09.22","Helles",2,"ut ipsum ac mi eleifend egestas. Sed pharetra, felis","/picture",18,"fortune outcome"),
  ("09.03.22","Stout",17,"interdum enim","/picture",11,"fortune outcome"),
  ("11.18.22","IPA",17,"accumsan interdum libero dui nec","/picture",25,"opportunity malt"),
  ("11.28.22","Bitter",18,"Proin","/picture",5,"idea ratio"),
  ("10.10.22","Pilsner",12,"pretium aliquet, metus urna convallis erat, eget tincidunt dui augue","/picture",10,"flight appearance"),
  ("10.19.22","Barley-Wine",9,"Nullam velit dui, semper et, lacinia","/picture",7,"moose twisted"),
  ("09.18.22","Pilsner",18,"justo sit amet nulla. Donec non justo. Proin","/picture",7,"indication lab"),
  ("10.08.22","Brown-Ale",16,"sit amet, consectetuer adipiscing elit. Etiam","/picture",19,"indication lab"),
  ("11.10.22","American-IPA",16,"at, iaculis","/picture",24,"outcome history"),
  ("09.01.22","Altbier",20,"lacus. Etiam bibendum fermentum","/picture",20,"ratio highway"),
  ("09.28.22","Pale-Lager",12,"nisi sem semper erat, in consectetuer ipsum nunc","/picture",17,"appearance indication"),
  ("09.23.22","Stout",5,"conubia nostra, per inceptos hymenaeos. Mauris ut quam","/picture",8,"history dinner"),
  ("09.29.22","Maerzen",15,"lectus, a sollicitudin orci sem eget massa. Suspendisse","/picture",13,"blue red"),
  ("10.17.22","Pale-Ale",4,"mauris sagittis placerat. Cras dictum ultricies ligula.","/picture",5,"strategy bread"),
  ("10.14.22","Helles",5,"neque. Morbi quis urna. Nunc","/picture",29,"idea ratio"),
  ("10.05.22","Maerzen",7,"lorem, eget mollis lectus","/picture",8,"guerilla craft"),
  ("11.17.22","Pilsner",7,"malesuada vel, venenatis","/picture",27,"grey blue"),
  ("10.26.22","Pale-Lager",20,"dui, in sodales elit erat vitae","/picture",11,"twisted passage"),
  ("09.25.22","Tripel",5,"Proin eget odio. Aliquam","/picture",23,"winner emotion"),
  ("10.13.22","Tripel",5,"fringilla purus mauris a nunc. In at pede. Cras","/picture",25,"chemistry control"),
  ("11.12.22","Doppelbock",17,"et magnis dis parturient montes, nascetur ridiculus mus.","/picture",13,"indication lab"),
  ("11.21.22","Amber-Ale",7,"et","/picture",22,"emotion grey"),
  ("10.27.22","American-IPA",15,"sapien.","/picture",25,"chemistry control"),
  ("11.22.22","Doppelbock",18,"nunc id enim.","/picture",20,"orange depth"),
  ("11.04.22","Ale",4,"mauris id sapien. Cras dolor dolor,","/picture",26,"orange depth"),
  ("09.23.22","Pale-Lager",5,"risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.","/picture",27,"idea ratio"),
  ("09.27.22","Brown-Ale",6,"sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed","/picture",29,"orange depth"),
  ("11.21.22","Stout",5,"dolor vitae dolor. Donec fringilla. Donec feugiat","/picture",7,"moose twisted"),
  ("09.29.22","Brown-Ale",13,"facilisis. Suspendisse commodo tincidunt nibh.","/picture",23,"blue red"),
  ("09.12.22","Altbier",8,"ad litora torquent","/picture",10,"blue red"),
  ("09.21.22","Doppelbock",11,"enim. Mauris quis turpis vitae purus gravida","/picture",23,"highway loss"),
  ("11.06.22","Tripel",11,"tristique senectus","/picture",14,"moose twisted"),
  ("11.26.22","IPA",9,"a","/picture",25,"passage brewing"),
  ("10.12.22","Amber-Ale",2,"adipiscing,","/picture",10,"law fortune"),
  ("09.09.22","Bitter",6,"sed orci lobortis augue scelerisque mollis. Phasellus libero","/picture",25,"dinner people"),
  ("09.15.22","Ale",16,"molestie. Sed id risus quis diam","/picture",9,"guerilla craft"),
  ("11.04.22","Bitter",2,"congue turpis. In","/picture",14,"dinner people"),
  ("09.23.22","Fruit-Beer",7,"ullamcorper, nisl arcu iaculis enim, sit amet","/picture",5,"moose twisted"),
  ("09.25.22","Schwarzbier",5,"turpis. Nulla aliquet.","/picture",6,"idea ratio");
