CREATE DATABASE IF NOT EXISTS dejabrew;
USE dejabrew;

DROP TABLE IF EXISTS Bar;
CREATE TABLE Bar (
    BarID     INT NOT NULL AUTO_INCREMENT,
    Details   NVARCHAR(60),
    DateAdded DATE,
    Name      NVARCHAR(60),
    Rating    DECIMAL,
    Picture   NVARCHAR(60),
    Location  NVARCHAR(60),
    PRIMARY KEY (BarID)
);

DROP TABLE IF EXISTS Beer;
CREATE TABLE Beer (
    BeerID    INT NOT NULL AUTO_INCREMENT ,
    DateAdded DATE,
    Type      NVARCHAR(40),
    Cost      DOUBLE,
    Comments  NVARCHAR(60),
    Picture   NVARCHAR(60),
    AlcVol    DOUBLE,
    Name      NVARCHAR(60),
    PRIMARY KEY (BeerID)
);

DROP TABLE IF EXISTS Brewery;
CREATE TABLE Brewery (
    BreweryID INT NOT NULL AUTO_INCREMENT,
    Name      NVARCHAR(60),
    Type      NVARCHAR(40),
    Picture   NVARCHAR(60),
    Location  NVARCHAR(60),
    DateAdded DATE,
    Details   NVARCHAR(60),
    PRIMARY KEY ( BreweryID )
);

DROP TABLE IF EXISTS Person;
CREATE TABLE Person (
    PID     INT NOT NULL AUTO_INCREMENT,
    Name    NVARCHAR(60),
    Picture NVARCHAR(60),
    PRIMARY KEY ( PID )
);

DROP TABLE IF EXISTS Tab;
CREATE TABLE Tab (
    TabID INT NOT NULL AUTO_INCREMENT,
    Total INT,
    PRIMARY KEY ( TabID )
);

DROP TABLE IF EXISTS Brews;
CREATE TABLE Brews (
    BrewID    INT NOT NULL AUTO_INCREMENT,
    BreweryID INT,
    FOREIGN KEY (BreweryID) REFERENCES Brewery (BreweryID),
    BeerID    INT ,
    FOREIGN KEY (BeerID) REFERENCES Beer (BeerID),
    PRIMARY KEY ( BrewID )
);

DROP TABLE IF EXISTS Buys;
CREATE TABLE Buys (
    BuyID  INT NOT NULL AUTO_INCREMENT,
    BeerID INT ,
    FOREIGN KEY (BeerID) REFERENCES Beer (BeerID),
    BarID  INT ,
    FOREIGN KEY (BarID) REFERENCES Bar (BarID),
    PRIMARY KEY ( BuyID )
);

DROP TABLE IF EXISTS Claim;
CREATE TABLE Claim (
    ClaimID INT NOT NULL AUTO_INCREMENT,
    BarID   INT ,
    FOREIGN KEY (BarID) REFERENCES Bar (BarID),
    TabID   INT ,
    FOREIGN KEY (TabID) REFERENCES Tab (TabID),
    PRIMARY KEY ( ClaimID )
);

DROP TABLE IF EXISTS Pay;
CREATE TABLE Pay (
    PayID INT NOT NULL AUTO_INCREMENT,
    TabID INT,
    FOREIGN KEY (TabID) REFERENCES Tab (TabID),
    PID   INT ,
    FOREIGN KEY (PID) REFERENCES Person (PID),
    PRIMARY KEY ( PayID )
);

DROP TABLE IF EXISTS Tablist;
CREATE TABLE TabList (
    ListID   INT NOT NULL AUTO_INCREMENT,
    BeerID   INT ,
    FOREIGN KEY (BeerID) REFERENCES Beer (BeerID),
    TabID    INT ,
    FOREIGN KEY (TabID) REFERENCES Tab (TabID),
    Quantity INT,
    Rating   DOUBLE,
    PRIMARY KEY ( ListID )
);
