INSERT INTO Bar (Details,DateAdded,Name,Rating,Picture,Location)
VALUES
  ("in consectetuer ipsum nunc id","09.30.22","piano opportunity malt",3,"/picture","South Burlington"),
  ("gravida sit amet, dapibus id,","09.06.22","green place",2,"/picture","Pocatello"),
  ("faucibus. Morbi","10.07.22","grey blue",3,"/picture","Tuscaloosa"),
  ("Nullam vitae diam. Proin dolor. Nulla semper tellus id","10.30.22","orange depth",2,"/picture","North Las Vegas"),
  ("magna a","10.20.22","ale combination owner",5,"/picture","Bozeman"),
  ("orci tincidunt adipiscing.","11.14.22","wealth strategy",2,"/picture","Kansas City"),
  ("urna suscipit nonummy. Fusce fermentum","11.12.22","opportunity malt",2,"/picture","Wilmington"),
  ("bibendum sed, est. Nunc","10.25.22","control piano opportunity",2,"/picture","Chattanooga"),
  ("Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus","09.12.22","law fortune",4,"/picture","Huntsville"),
  ("malesuada malesuada. Integer id magna et","11.26.22","combination owner",1,"/picture","Louisville"),
  ("venenatis a, magna. Lorem ipsum dolor sit amet,","10.24.22","grey blue",1,"/picture","Lansing"),
  ("aliquet. Phasellus","09.16.22","history dinner",5,"/picture","Duluth"),
  ("a purus. Duis elementum, dui quis accumsan convallis,","10.29.22","strategy bread",5,"/picture","San Antonio"),
  ("vehicula aliquet libero. Integer in magna.","10.08.22","red green",3,"/picture","Gulfport"),
  ("risus. Donec egestas. Duis ac arcu. Nunc","10.06.22","blue red",1,"/picture","Kearney"),
  ("pede blandit congue. In scelerisque scelerisque dui. Suspendisse","09.27.22","combination owner storage",3,"/picture","Aurora"),
  ("posuere, enim nisl elementum purus, accumsan interdum libero","11.17.22","place beers",2,"/picture","Tampa"),
  ("purus mauris","11.18.22","bread idea",4,"/picture","Ketchikan"),
  ("egestas. Aliquam fringilla cursus purus. Nullam scelerisque","09.28.22","brewing company",3,"/picture","Erie"),
  ("tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris","11.21.22","orange depth flight",0,"/picture","Newark");

INSERT INTO Beer (DateAdded,Type,Cost,Comments,Picture,AlcVol,Name)
VALUES
  ("10.13.22","Amber-Ale",12,"est arcu ac orci. Ut","/picture",4,"company guerilla"),
  ("09.16.22","Pale-Ale",15,"placerat eget, venenatis a, magna. Lorem ipsum dolor","/picture",28,"appearance indication"),
  ("10.24.22","Barley-Wine",18,"Nulla tincidunt, neque vitae semper","/picture",22,"chemistry control"),
  ("09.21.22","Ale",4,"mauris, aliquam eu, accumsan sed, facilisis vitae, orci.","/picture",8,"appearance indication"),
  ("11.24.22","Stout",7,"imperdiet non, vestibulum nec, euismod","/picture",13,"idea ratio"),
  ("11.04.22","Altbier",7,"Proin sed turpis nec mauris blandit","/picture",5,"outcome history"),
  ("09.02.22","Altbier",6,"neque. Sed","/picture",12,"lab chemistry"),
  ("10.04.22","Altbier",7,"tempus eu, ligula. Aenean euismod","/picture",11,"mud law"),
  ("09.29.22","Witbier",7,"molestie. Sed id risus quis diam luctus","/picture",5,"contribution orange"),
  ("09.16.22","Imperial-Stout",9,"metus. In lorem. Donec elementum, lorem ut aliquam iaculis,","/picture",20,"blue red"),
  ("11.20.22","Fruit-Beer",4,"torquent per conubia nostra,","/picture",17,"grey blue"),
  ("10.09.22","Helles",2,"ut ipsum ac mi eleifend egestas. Sed pharetra, felis","/picture",18,"fortune outcome"),
  ("09.03.22","Stout",17,"interdum enim","/picture",11,"fortune outcome"),
  ("11.18.22","IPA",17,"accumsan interdum libero dui nec","/picture",25,"opportunity malt"),
  ("11.28.22","Bitter",18,"Proin","/picture",5,"idea ratio"),
  ("10.10.22","Pilsner",12,"pretium aliquet, metus urna convallis erat, eget tincidunt dui augue","/picture",10,"flight appearance"),
  ("10.19.22","Barley-Wine",9,"Nullam velit dui, semper et, lacinia","/picture",7,"moose twisted"),
  ("09.18.22","Pilsner",18,"justo sit amet nulla. Donec non justo. Proin","/picture",7,"indication lab"),
  ("10.08.22","Brown-Ale",16,"sit amet, consectetuer adipiscing elit. Etiam","/picture",19,"indication lab"),
  ("11.10.22","American-IPA",16,"at, iaculis","/picture",24,"outcome history"),
  ("09.01.22","Altbier",20,"lacus. Etiam bibendum fermentum","/picture",20,"ratio highway"),
  ("09.28.22","Pale-Lager",12,"nisi sem semper erat, in consectetuer ipsum nunc","/picture",17,"appearance indication"),
  ("09.23.22","Stout",5,"conubia nostra, per inceptos hymenaeos. Mauris ut quam","/picture",8,"history dinner"),
  ("09.29.22","Maerzen",15,"lectus, a sollicitudin orci sem eget massa. Suspendisse","/picture",13,"blue red"),
  ("10.17.22","Pale-Ale",4,"mauris sagittis placerat. Cras dictum ultricies ligula.","/picture",5,"strategy bread"),
  ("10.14.22","Helles",5,"neque. Morbi quis urna. Nunc","/picture",29,"idea ratio"),
  ("10.05.22","Maerzen",7,"lorem, eget mollis lectus","/picture",8,"guerilla craft"),
  ("11.17.22","Pilsner",7,"malesuada vel, venenatis","/picture",27,"grey blue"),
  ("10.26.22","Pale-Lager",20,"dui, in sodales elit erat vitae","/picture",11,"twisted passage"),
  ("09.25.22","Tripel",5,"Proin eget odio. Aliquam","/picture",23,"winner emotion"),
  ("10.13.22","Tripel",5,"fringilla purus mauris a nunc. In at pede. Cras","/picture",25,"chemistry control"),
  ("11.12.22","Doppelbock",17,"et magnis dis parturient montes, nascetur ridiculus mus.","/picture",13,"indication lab"),
  ("11.21.22","Amber-Ale",7,"et","/picture",22,"emotion grey"),
  ("10.27.22","American-IPA",15,"sapien.","/picture",25,"chemistry control"),
  ("11.22.22","Doppelbock",18,"nunc id enim.","/picture",20,"orange depth"),
  ("11.04.22","Ale",4,"mauris id sapien. Cras dolor dolor,","/picture",26,"orange depth"),
  ("09.23.22","Pale-Lager",5,"risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.","/picture",27,"idea ratio"),
  ("09.27.22","Brown-Ale",6,"sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed","/picture",29,"orange depth"),
  ("11.21.22","Stout",5,"dolor vitae dolor. Donec fringilla. Donec feugiat","/picture",7,"moose twisted"),
  ("09.29.22","Brown-Ale",13,"facilisis. Suspendisse commodo tincidunt nibh.","/picture",23,"blue red"),
  ("09.12.22","Altbier",8,"ad litora torquent","/picture",10,"blue red"),
  ("09.21.22","Doppelbock",11,"enim. Mauris quis turpis vitae purus gravida","/picture",23,"highway loss"),
  ("11.06.22","Tripel",11,"tristique senectus","/picture",14,"moose twisted"),
  ("11.26.22","IPA",9,"a","/picture",25,"passage brewing"),
  ("10.12.22","Amber-Ale",2,"adipiscing,","/picture",10,"law fortune"),
  ("09.09.22","Bitter",6,"sed orci lobortis augue scelerisque mollis. Phasellus libero","/picture",25,"dinner people"),
  ("09.15.22","Ale",16,"molestie. Sed id risus quis diam","/picture",9,"guerilla craft"),
  ("11.04.22","Bitter",2,"congue turpis. In","/picture",14,"dinner people"),
  ("09.23.22","Fruit-Beer",7,"ullamcorper, nisl arcu iaculis enim, sit amet","/picture",5,"moose twisted"),
  ("09.25.22","Schwarzbier",5,"turpis. Nulla aliquet.","/picture",6,"idea ratio");

INSERT INTO Brewery (Name,Type,Picture,Location,DateAdded,Details)
VALUES
  ("owner storage","micro","/picture","Milwaukee","09.24.22","fringilla. Donec feugiat metus sit amet ante. Vivamus"),
  ("lab chemistry","brewpub","/picture","West Jordan","11.27.22","sollicitudin orci sem eget massa. Suspendisse eleifend. Cras"),
  ("contribution orange","taproom","/picture","Dover","11.21.22","mollis non, cursus non, egestas"),
  ("idea ratio","regional","/picture","Fort Worth","09.29.22","nec urna suscipit nonummy."),
  ("grey blue","brewpub","/picture","Norman","10.14.22","eu tellus eu augue"),
  ("ratio highway","micro","/picture","Chesapeake","09.05.22","aliquet vel, vulputate eu, odio. Phasellus at augue"),
  ("storage bird","taproom","/picture","Jefferson City","10.29.22","orci. Phasellus dapibus quam"),
  ("flight appearance","brewpub","/picture","Auburn","09.10.22","pretium neque. Morbi quis urna. Nunc"),
  ("lab chemistry","taproom","/picture","South Burlington","09.02.22","Duis gravida. Praesent eu nulla at sem molestie"),
  ("winner emotion","brewpub","/picture","Warren","11.12.22","metus sit amet ante. Vivamus");

INSERT INTO Person (Name,Picture)
VALUES
  ("Boris Chen","/picture"),
  ("Jordan Carroll","/picture"),
  ("Olivia Burgess","/picture"),
  ("Alana Park","/picture"),
  ("Margaret Mosley","/picture"),
  ("Uma Meadows","/picture"),
  ("Isadora Crawford","/picture"),
  ("Quinn Pittman","/picture"),
  ("Shay Puckett","/picture"),
  ("Cole Mathis","/picture"),
  ("Basil Hanson","/picture"),
  ("Eve Thompson","/picture"),
  ("Ciaran Coffey","/picture"),
  ("Candace Sampson","/picture"),
  ("Miranda Mathews","/picture"),
  ("Yasir Benton","/picture"),
  ("Kato Lawrence","/picture"),
  ("Igor Sargent","/picture"),
  ("Sage Wallace","/picture"),
  ("Gloria Ochoa","/picture");

INSERT INTO Tab (Total)
VALUES
  (36),
  (6),
  (12),
  (11),
  (24),
  (27),
  (27),
  (14),
  (38),
  (11),
  (37),
  (38),
  (1),
  (26),
  (25),
  (11),
  (19),
  (1),
  (18),
  (12),
  (9),
  (34),
  (34),
  (16),
  (7),
  (20),
  (21),
  (39),
  (40),
  (34),
  (39),
  (9),
  (2),
  (16),
  (24),
  (9),
  (4),
  (1),
  (12),
  (31),
  (2),
  (28),
  (2),
  (28),
  (28);
